=== eksiir/streaming-data-manager/Consumer/src/main/resources/ConsumerConfigSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.eksiir.com/consumer" xmlns="http://www.eksiir.com/consumer">
  <xs:element name="StreamingDataConsumer" type="StreamingDataConsumerType">
  </xs:element>
  <xs:complexType name="ConnectorType">
    <xs:sequence>
      <xs:element type="xs:string" name="Type"/>
      <xs:element type="xs:string" name="S3Bucket"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="KinesisType">
    <xs:sequence>
      <xs:element type="xs:string" name="Region"/>
      <xs:element type="xs:string" name="EndPoint"/>
      <xs:element type="xs:string" name="CredentialsPropertiesFileName"/>
      <xs:element type="xs:string" name="StreamName"/>
      <xs:element type="ConsumerType" name="Consumer"/>
      <xs:element type="ConnectorType" name="Connector"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="StreamingDataType">
    <xs:sequence>
      <xs:element type="xs:string" name="Carrier"/>
      <xs:element type="xs:string" name="Model"/>
      <xs:element type="xs:string" name="Delimiter"/>
      <xs:element type="xs:string" name="ConsumerProcessor"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="context"/>
  </xs:complexType>
  <xs:complexType name="StreamingDataConsumerType">
    <xs:sequence>
      <xs:element type="StreamingDataType" name="StreamingData"/>
      <xs:element type="KinesisType" name="Kinesis"/>
      <xs:element type="RedshiftType" name="Redshift"/>
      <xs:element type="S3Type" name="S3"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="S3Type">
    <xs:sequence>
      <xs:element type="xs:string" name="EndPoint"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ConsumerType">
    <xs:sequence>
      <xs:element type="xs:string" name="UniqueApplicationName"/>
      <xs:element type="xs:string" name="InitialPositionInStream"/>
      <xs:element type="xs:string" name="NumRetries"/>
      <xs:element type="xs:string" name="MaxRecordsNotCheckPointed"/>
      <xs:element type="xs:string" name="CheckpointIntervalMillis"/>
      <xs:element type="xs:string" name="BackOffTimeMillis"/>
      <xs:element type="xs:string" name="CharacterSet"/>
      <xs:element type="xs:string" name="MinRecordsPerBuffer"/>
      <xs:element type="xs:string" name="MinBytesPerBuffer"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="RedshiftType">
    <xs:sequence>
      <xs:element type="xs:string" name="EndPoint"/>
      <xs:element type="xs:string" name="CredentialsFileName"/>
      <xs:element type="xs:string" name="TableName"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== eksiir/streaming-data-manager/Consumer/target/classes/DefaultConsumerConfig.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!--
    This is the default streaming data consumer configuration file.
    The values here can be overwritten by a customized configuration file passed to the consumer executable or library.

    Created by bbehzadi on 2/10/14.
-->
<StreamingDataConsumer xmlns="http://www.eksiir.com/consumer"
                       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                       xsi:schemaLocation="http://www.eksiir.com/consumer ConsumerConfigSchema.xsd">

    <StreamingData context="consumer">
        <Carrier>KINESIS</Carrier>
        <Model>ORDER</Model>
        <Delimiter>|</Delimiter>
        <ConsumerProcessor>KINESIS_REDSHIFT_CONNECTOR</ConsumerProcessor>
    </StreamingData>
    <Kinesis>
        <Region>us-east-1</Region>
        <EndPoint>https://kinesis.us-east-1.amazonaws.com</EndPoint>
        <CredentialsPropertiesFileName>AwsCredentials.properties</CredentialsPropertiesFileName>
        <StreamName>Orders</StreamName>
        <Consumer>
            <UniqueApplicationName>Orders-KINESIS_REDSHIFT_CONNECTOR-LATEST</UniqueApplicationName>
            <InitialPositionInStream>LATEST</InitialPositionInStream>
            <NumRetries>10</NumRetries>
            <MaxRecordsNotCheckPointed>1000</MaxRecordsNotCheckPointed>
            <CheckpointIntervalMillis>60000</CheckpointIntervalMillis>
            <BackOffTimeMillis>3000</BackOffTimeMillis>
            <CharacterSet>UTF-8</CharacterSet>
            <MinRecordsPerBuffer>1000</MinRecordsPerBuffer>
            <MinBytesPerBuffer>1048576</MinBytesPerBuffer>
        </Consumer>
        <Connector>
            <Type>Redshift</Type>
            <S3Bucket>streaming-data</S3Bucket>
        </Connector>
    </Kinesis>
    <Redshift>
        <EndPoint>https://redshift.us-east-1.amazonaws.com</EndPoint>
        <CredentialsFileName>RedshiftCredentials.properties</CredentialsFileName>
        <TableName>kinesis_test</TableName>
    </Redshift>
    <S3>
        <EndPoint>https://s3.amazonaws.com</EndPoint>
    </S3>
</StreamingDataConsumer>
