=== eksiir/streaming-data-manager/Producer/src/main/resources/ProducerConfigSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.eksiir.com/producer" xmlns="http://www.eksiir.com/producer">
  <xs:element name="StreamingDataProducer" type="StreamingDataProducerType">
  </xs:element>
  <xs:complexType name="KinesisType">
    <xs:sequence>
      <xs:element type="xs:string" name="Region"/>
      <xs:element type="xs:string" name="EndPoint"/>
      <xs:element type="xs:string" name="CredentialsPropertiesFileName"/>
      <xs:element type="xs:string" name="StreamName"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="StreamingDataType">
    <xs:sequence>
      <xs:element type="xs:string" name="Source"/>
      <xs:element type="xs:string" name="Carrier"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="context"/>
  </xs:complexType>
  <xs:complexType name="LogTailerType">
    <xs:sequence>
      <xs:element type="xs:string" name="Filename"/>
      <xs:element type="xs:string" name="MillisecDelay"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="StreamingDataProducerType">
    <xs:sequence>
      <xs:element type="StreamingDataType" name="StreamingData"/>
      <xs:element type="LogTailerType" name="LogTailer"/>
      <xs:element type="KinesisType" name="Kinesis"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== eksiir/streaming-data-manager/Producer/target/classes/DefaultProducerConfig.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!--
    This is the default streaming data producer configuration file.
    The values here can be overwritten by a customized configuration file passed to the producer executable or library.

    Created by bbehzadi on 2/10/14.
-->
<StreamingDataProducer xmlns="http://www.eksiir.com/producer"
                       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                       xsi:schemaLocation="http://www.eksiir.com/producer ProducerConfigSchema.xsd">
    <StreamingData context="producer">
        <Source>LOG_FILE</Source>
        <Carrier>KINESIS</Carrier>
    </StreamingData>
    <LogTailer>
        <Filename>/tmp/log.out</Filename>
        <MillisecDelay>0</MillisecDelay>
    </LogTailer>
    <Kinesis>
        <Region>us-east-1</Region>
        <EndPoint>https://kinesis.us-east-1.amazonaws.com</EndPoint>
        <CredentialsPropertiesFileName>AwsCredentials.properties</CredentialsPropertiesFileName>
        <StreamName>Orders</StreamName>
    </Kinesis>
</StreamingDataProducer>
